sudo: false
addons:
  apt:
    packages:
      - redis-server
language: c
compiler:
  - gcc
  - clang
before_script:
  - redis-server --port 6379 &
  - redis-server --port 6380 --requirepass 'secret' &
  - redis-server --cluster-enabled yes --cluster-config-file 7000-nodes.conf --port 7000 &
  - redis-server --cluster-enabled yes --cluster-config-file 7001-nodes.conf --port 7001 &
  - redis-server --cluster-enabled yes --cluster-config-file 7002-nodes.conf --port 7002 &
  - redis-server --cluster-enabled yes --cluster-config-file 7003-nodes.conf --port 7003 &
  - redis-server --cluster-enabled yes --cluster-config-file 7004-nodes.conf --port 7004 &
  - redis-server --cluster-enabled yes --cluster-config-file 7005-nodes.conf --port 7005 &
  - echo yes | redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005
script:
  - rake test
