version: '2'
services:
  redis:
    image: redis:5.0.3
    command: 'redis-server --port 6379'
    ports:
      - '6379:6379'

  redis-secure:
    image: redis:5.0.3
    command: 'redis-server --port 6380 --requirepass "secret"'
    ports:
      - '6380:6380'

  redis-cluster:
    environment:
      IP: ${REDIS_CLUSTER_IP}
      SENTINEL: ${REDIS_USE_SENTINEL}
      STANDALONE: ${REDIS_USE_STANDALONE}
    hostname: server
    image: 'grokzen/redis-cluster:5.0.3'
    ports:
      - '7000-7007:7000-7007'
      - '5000-5002:5000-5002'
